version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version
  - dotnet --info

build_script:
  - dotnet restore src
  - dotnet publish src -c Release -o out
  - docker build -t api-internal src

deploy_script:
  - docker login -u="middlemarsh29" -p="Welcome$00"
  - docker tag api-internal middlemarsh29/payments.api.internal:1.0.{build}
  - docker push middlemarsh29/payments.api.internal:1.0.{build}