version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version
  - dotnet --info

build_script:
  - dotnet restore src
  - dotnet publish src -c Release -o out
  - docker build -t api-internal src